### ISSUE TITLE
ResourceUnitCost not correctly calculated

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [blowfishpro/B9PartSwitch#10]
It needs to take into account the unitsPerVolume of each resource as well, so [line 61](https://github.com/blowfishpro/B9PartSwitch/blob/5c09194631a75b3e00946acfb7b66abce49c5482/B9PartSwitch/TankSettings/Tanks.cs#L61) should be:

```
public float ResourceUnitCost => resources.Sum(r => (r.resourceDefinition.unitCost) * (r.unitsPerVolume) );
```

**Comment by blowfishpro** [comment]
Nice catch!  Fix released.
