### ISSUE TITLE
Log warning with only one subtype

### ISSUE THREAD

**Issue by jsolson** [blowfishpro/B9PartSwitch#114]
Should I be concerned about this?

~~~
[WRN 19:53:49.699] [WARNING] [Part bluedog.Apollo.AARDV.Cargo] [ModuleB9PartSwitch 'cargoSwitch'] Only one subtype found, this may lead to unexpected behavior
~~~

We use Ore as a placeholder to define the volume on cargo parts. What gets added to the SUBTYPE's depends on what life support mods are installed, if any are.

**Comment by blowfishpro** [comment]
Yeah, it occurred to me last night that this might be easier than trying to selectively add `ModuleB9PartSwitch` based on one of several mods being present.  I think it works fine so I guess it makes sense for it to be a supported use case and just disable the UI when it happens?

**Comment by jsolson** [comment]
You could leave the UI. It advertises to the user the part could do more than be an Ore container if they wanted. I had envisioned someone using a personal patch to make cargo subtypes for whatever their need is.
