### ISSUE TITLE
fuzzy logic for node toggling please

### ISSUE THREAD

**Issue by Jiraiyah** [blowfishpro/B9PartSwitch#126]
Hi
I may be a special case for you, but, my mods have tons of nodes that i toggle on/off using part switch, without a fuzzy logic for node selection, the config becomes over thousands of lines while if there was a fuzzy logic to select nodes like : ringOut* or *900 it would make the config much smaller (most likely 100 lines nothing more !)

Please if it's possible, add a fuzzy logic for something like this in future updates. thanks

**Comment by blowfishpro** [comment]
Done in 7913f72
