### ISSUE TITLE
Hang at the VAB and crash at startup

### ISSUE THREAD

**Issue by artyom-y-razinov** [blowfishpro/B9PartSwitch#13]
I've originally posted bugs on KSP bugtracker, but then realized that the only mod that causes this issue is B9PartSwitch (with many configurations of mods adding B9PartSwitch causes bugs, removing it makes KSP run perfectly).

There are logs, sampling, used mods and other info:
http://bugs.kerbalspaceprogram.com/issues/9721
http://bugs.kerbalspaceprogram.com/issues/9725

This reproduces on OSX (all info is in those invalid bugreports for vanilla KSP).

If you need more info, ask me.

**Comment by blowfishpro** [comment]
If there's a crash, I need to see your full KSP.log from right after the crash occurs.

As for performance issues, are you doing anything in particular before the hangs, or do they happen periodically without user input?

**Comment by blowfishpro** [comment]
More information I need: in the editor, does it only happen when specific parts are placed (i.e. those with switchers), or no? If you open up the debug output in-game (Alt+F12, click debug, scroll to the bottom), do you see specific messages pop up right before KSP hangs?

**Comment by artyom-y-razinov** [comment]
Ok, I'll give you more info later, never mind about this until I do that. I've experienced same issue after updating some other mod (and I had no problems for many hours of gameplay until today).
