### ISSUE TITLE
PAW button "Part Info" doesn't do anything

### ISSUE THREAD

**Issue by linuxgurugamer** [blowfishpro/B9PartSwitch#140]
If there is nothing for it to do, then it shouldn't be shown

**Comment by blowfishpro** [comment]
Is this still an issue?  The button seems to be hidden for parts that don't need it now.

**Comment by Gordon-Dry** [comment]
I've seen this button with KSP 1.6.1 several times and it didn't do anything when clicked.

**Comment by blowfishpro** [comment]
It was working on 1.7.1 yesterday when I tried it.  Can you show a ConfigCache entry for a part for which it doesn't seem to do anything?

**Comment by Gordon-Dry** [comment]
Within the last 3 hours I was not able to get that reproduced.
