### ISSUE TITLE
Project set to target .NETFramework 4.7.1

### ISSUE THREAD

**Issue by linuxgurugamer** [blowfishpro/B9PartSwitch#141]
Loading the mod into VS:
The C# project "B9PartSwitchTests" is targeting ".NETFramework,Version=v4.7.1", which is not installed on this machine.....

However, the B9PartSwitch is set to .Net 3.5

**Comment by blowfishpro** [comment]
I discovered it needs .NET 4+ to run tests, not exactly sure why.  But of course regular B9PartSwitch needs to still be on .NET 3.5 to run in KSP.  Everything works fine if you have .NET 4.7.1 installed

**Comment by blowfishpro** [comment]
So just to clarify, this is intended

**Comment by linuxgurugamer** [comment]
Ok, thanks.
