### ISSUE TITLE
Request: Part info panel titles

### ISSUE THREAD

**Issue by jsolson** [blowfishpro/B9PartSwitch#144]
"Switchable `<switcherDescription>`" would be clearer than "Switchable Part" when there's more than one. There are times I look at my own parts and can't tell what they do from that pane.

![Untitled](https://user-images.githubusercontent.com/16825376/57464024-f596f180-7249-11e9-8ad4-7b716bc7b676.png)

**Comment by blowfishpro** [comment]
I actually used to have this.  The trouble is that it also affects the filter by module functionality, so you end up with one thing there for every unique title.  Maybe that matters less though.

**Comment by jsolson** [comment]
Maybe "4 Fuel Subtypes" instead of "4 Subtypes" then.

It's no big deal.

**Comment by blowfishpro** [comment]
If you change `switcherDescriptionPlural` it should change that line (so if you set it to `Tank Types` then it will say `4 Tank Types`)
