### ISSUE TITLE
Feature Request:  Add ability to change the scale of a model

### ISSUE THREAD

**Issue by linuxgurugamer** [blowfishpro/B9PartSwitch#145]
I'm looking to eliminate the need for Tweakscale for some parts.
I'd like the ability to specify a scaling factor to a transform.  The idea is to not use TweakScale, but emulate in a poor man's way what it does.  I don't mind specifying the values which will need to be changed, and scaling the model is the only thing I don't see here.

Per forum post

**Comment by blowfishpro** [comment]
Does it need different scaling on each axis or uniform?

**Comment by linuxgurugamer** [comment]
Ummm, for me, uniform, but I would suppose that if you can do it, then to implement the same functionality as the:

scale = 1.25, 1.25, 1.25

line which appears in the model
