### ISSUE TITLE
UI switcher screws up indices with tech limits

### ISSUE THREAD

**Issue by blowfishpro** [blowfishpro/B9PartSwitch#173]
this index will be wrong since the counter keeps incrementing even for a skipped subtype:
https://github.com/blowfishpro/B9PartSwitch/blob/1fb57d99208dace74522417c5cc6798906bc51fa/B9PartSwitch/UI/UIPartActionSubtypeSelector.cs#L77

this index is not correct since the number of unlocked subtypes may be less than the actual number of subtypes:
https://github.com/blowfishpro/B9PartSwitch/blob/1fb57d99208dace74522417c5cc6798906bc51fa/B9PartSwitch/UI/UIPartActionSubtypeSelector.cs#L98

**Comment by Gordon-Dry** [comment]
Yeah, sometimes I'm not "just complaining" - I'm a bughunter.
Well, mostly.
In my opinion at least.
;)
