### ISSUE TITLE
Feature Request: PAW groups

### ISSUE THREAD

**Issue by SirMortimer** [blowfishpro/B9PartSwitch#184]
It would be very nice (and help clean up the PAW) if we were able to put the switch buttons into PAW action groups (the list switch and the button that opens the switch dialog). The PAW group UI name should be configurable.

**Comment by blowfishpro** [comment]
Okay the word "action groups" in the title was confusing but I know what you're talking about now.  A few things:

* I may combine the button into the other switching UI element (or eliminate it entirely at some point).  Is this still valuable in that scenario?
* Most other modules don't support this including most of the stock modules.  Is it still valuable given that most other things can't be added to the groups?

**Comment by SirMortimer** [comment]
Ah, sorry for the confusing title.
As to your questions: 

- I would prefer not having the extra button (the one that opens the dialog), maybe have an option to hide it, even hide it by default. But when it is visible, it should be in the same PAW group as the switching element. 
- Is it possible to not have a group if it is not configured? I know it is fairly straight forward with the usual garden variety PAW button, but I don't know if the switcher element needs some extra care to handle the reduced horizontal space within a group. If having the group would be optional (opt-in) that would be ideal, if not that would be... unfortunate, but in that case I'd rather have it than not.

**Comment by blowfishpro** [comment]
Not sure if that really answers the 2nd question.  Of course it would be optional and fully configurable.  But what else do you plan to put in those groups and how?

**Comment by SirMortimer** [comment]
These are the current use cases. We use B9PS to switch the configuration for experiment part modules and life support processes.

Switchable experiments on a probe core, there already is a "Science" section that has information about hard drives, and the activated science experiments themselves (when selected, see crew report in next screenshot)

<img width="485" alt="a" src="https://user-images.githubusercontent.com/43166475/76652591-3137d180-6567-11ea-9815-7842bbed6644.png">

<img width="457" alt="c" src="https://user-images.githubusercontent.com/43166475/76652599-36951c00-6567-11ea-886c-e86c946c90b5.png">

The removed "Select" buttons would be most apparent here, where they currently fill about 1/3rd of the PAW. It's a fairly complex part.

<img width="485" alt="b" src="https://user-images.githubusercontent.com/43166475/76652595-34cb5880-6567-11ea-9c2f-3320a4cd7982.png">

**Comment by blowfishpro** [comment]
The reason for keeping the button for the moment is that the subtype switcher is annoying to use, and there's no way to see the names of all the subtypes at once.

The best solution is probably to merge the button into the existing UI element.  I'm already screwing with the subtype switcher thing to get it to work, just a question of making more modifications.

So you'll mostly be using it with custom modules that either already have or can have group support?

**Comment by blowfishpro** [comment]
Another question, do you care about `startCollapsed`?

**Comment by SirMortimer** [comment]
> So you'll mostly be using it with custom modules that either already have or can have group support?

Yes.

> Another question, do you care about startCollapsed?

Not particularly. I might use it if it is there, but the goal is having a PAW that is small enough to not need default collapsed groups.

**Comment by blowfishpro** [comment]
Done #190
