### ISSUE TITLE
Getting a fatal exception error when I try to use this mod and Stockalike Station Parts Redux

### ISSUE THREAD

**Issue by Will-Nichols** [blowfishpro/B9PartSwitch#191]
I am getting this error now and am not sure if it is from SPSXr or B9 Parts Switcher...nothing is showing up in the log file as its asking me to check unless there is a different log somewhere else.

[Image 1](https://gyazo.com/a0e261835483a9248978f06f4644e1c9)

[Image 2](https://gyazo.com/e2710009f747c0eb0feaf4f904355499)

**Comment by blowfishpro** [comment]
Do you have Community Resource Pack installed?  That is a dependency of your installed mods.

If that's not the problem I need logs as usual.

**Comment by Will-Nichols** [comment]
I do but I pulled Stockalike Station Parts Redux out of the mod list to load and its actually loading now. I went to pull the log files and nothing was listed in the log file at all. I am trying to load it again and see if it will generate a log file.

**Comment by Will-Nichols** [comment]
Here is a link to the [player log file](https://www.dropbox.com/s/j9p4uzcj66w04s2/Player.log?dl=0).

**Comment by Will-Nichols** [comment]
Also here is a screenshot of the modlist I am loading. 
https://gyazo.com/725a212d99a6191cda69720670b1a8f5

**Comment by blowfishpro** [comment]
`GameData/CommunityResourcePack/CommonResources.cfg` seems to be missing a bunch of entries.  Try re-installing CRP

**Comment by Will-Nichols** [comment]
I reloaded it and the game would not load and kept hanging on two other mod dll files. I ended up removing Routine Mission Manager and Civilian Population and once I removed those two mods the game loaded fine.
