### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by MaTTyLee9** [blowfishpro/B9PartSwitch#200]
I get an error with kerbal space program v1.9.1 getting a message saying that a tank called supplies doesn't exist

**Comment by blowfishpro** [comment]
Need more information to debug.  Just to be clear it's an issue with mods that depend on B9PartSwitch rather than an issue with B9PartSwitch itself.  Please provide your log and ModuleaManager.ConfigCache.

**Comment by MaTTyLee9** [comment]
[ModuleManager.log](https://github.com/blowfishpro/B9PartSwitch/files/4794517/ModuleManager.log)

**Comment by MaTTyLee9** [comment]
and i can't send my log because it is too big

**Comment by blowfishpro** [comment]
You can upload the log to something like Google Drive or Dropbox and then share it.

I need the ConfigCache (found in GameData) too.

**Comment by MaTTyLee9** [comment]
https://www.dropbox.com/s/307sfxsela12yb6/ModuleManager.ConfigCache?dl=0

**Comment by 7ranceaddic7** [comment]
@MaTTyLee9 Matty, Compress your KSP.log > KSP.log.7z/Zip that'll crunch it to about 2MB

**Comment by MaTTyLee9** [comment]
[KSP.zip](https://github.com/blowfishpro/B9PartSwitch/files/4806939/KSP.zip)

**Comment by 7ranceaddic7** [comment]
So,I'm gonna paraphrase what he's told me...

B9 is a BlackBox of sorts.

Stuff goes in.  Stuff comes out.

So, if you put garbage in, you're gonna get garbage out.

Your problem stems from SSPX. I'd recommend you (if you can) remove and replace SSPX.
The run KSP to the Start screen and quit.
Check the logs again.

Tell us what happens.

**Comment by MaTTyLee9** [comment]
works better thanks for the help

**Comment by 7ranceaddic7** [comment]
Good to hear, I love it when I can do that.  Enjoy !

That "remove, replace, restart" is a fantastic troubleshooting mechanism.
