### ISSUE TITLE
Remote version file is missing

### ISSUE THREAD

**Issue by HebaruSan** [blowfishpro/B9PartSwitch#205]
The version file's URL property currently is this, which doesn't exist:

- https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc/ksp-1.10.1/B9PartSwitch.version

Checking https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc , there are version files for other game versions, but not 1.10.1. Looks like maybe it never got uploaded?

Note that making multiple version-specific remote version files somewhat defeats the purpose of remote version files, because you lose the ability to notify about newer versions that are only reflected in newer remote version files. Recommend using one single remote version file to get back this capability.

Tagging @blowfishpro because I'm not sure whether GitHub will send a notification otherwise.

https://github.com/DasSkelett/AVC-VersionFileValidator by @DasSkelett can help a lot with catching things like this.

**Comment by blowfishpro** [comment]
Good catch, probably got missed when I moved over to Github actions

**Comment by HebaruSan** [comment]
Did this actually get fixed? The URL is still a 404:

https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc/ksp-1.10.1/B9PartSwitch.version

**Comment by blowfishpro** [comment]
Yeah that should be working, it has been a while since I released though

**Comment by blowfishpro** [comment]
(btw if you're curious there's an AWS lambda function that copies the version file to latest if it is in fact the latest version)
