### ISSUE TITLE
re-appearing b9ps

### ISSUE THREAD

**Issue by Fisheiyy** [blowfishpro/B9PartSwitch#206]
i delete b9partswitch and the next time i go to play ksp it reinstalls and gives me a fatal error so i have to hunt it down and delete it again what is doing this?

**Comment by blowfishpro** [comment]
Well it's definitely not B9PartSwitch itself.  But it sounds like you may have things installed at the wrong place, duplicates, etc which is probably why you're having issues.  Honestly my best advice would be to remove all mods (everything in GameData except for Squad and SquadExpansion) and start from scratch.

**Comment by Fisheiyy** [comment]
it only comes back here and there not sure from where but it does, seems to have stopped
