### ISSUE TITLE
B9part Switch - Serious Error "Could Not find matching Module"

### ISSUE THREAD

**Issue by yabegitu** [blowfishpro/B9PartSwitch#236]
![Screenshot (176)](https://user-images.githubusercontent.com/116003798/196407273-c8693091-1d95-41c7-88c7-f61f00b454ee.png)

This message keep appears, I don't know what to do, Can someone help about it??

**Comment by Rodg88** [comment]
Could be an installation issue with near future solar, double check that’s installed properly. Not a b9 bug though.

**Comment by yabegitu** [comment]
Alright, I will try to check

**Comment by Rodg88** [comment]
Probably unrelated. I'd need your KSP.log file to look further into it

**Comment by yabegitu** [comment]
Here, Also all solar panel are not working and i dont know the problem.
[KSP.log](https://github.com/blowfishpro/B9PartSwitch/files/9819283/KSP.log)

**Comment by Rodg88** [comment]
Seems like a few mods aren’t installed correctly or are missing dependencies. Eg multiple older module managers, no kopernicus for RSS, and folders directly in game data that should be inside other missing subfolders. it might be worth looking into CKAN mod manager to help install everything correctly.

**Comment by yabegitu** [comment]
The RSS don't any have file in it actually, Also can you tell me about the Mod that aren't installed Correctly? all of NearFutureTech last update was mostly 2021, thank you for helping tho😅

**Comment by Rodg88** [comment]
Maybe "aeon"? There shouldn't be folders like "Parts" or "Flags" directly in GameData, they should be in a subfolder per mod. If they aren't installed correctly, the parts won't load. 
And I think 'MultiStarSolarPanels.cfg in you gamedata' is a leftover from kopernicus which will be the cause of the solar panel issues.

**Comment by yabegitu** [comment]
I just knew it know some of them we're Incorrectly because the time when i download those mod is when i still new to KSP Mod, aeon is a Ore tank, Example : ELTankMedORE. Also do i need to delete "MultiStarSolarPanels.cfg" or something? Thanks for the Help and Info :D ( I will try this right away ).
