### ISSUE TITLE
Serious warning and Fatal error about CryoTanks

### ISSUE THREAD

**Issue by ELJOKER900** [blowfishpro/B9PartSwitch#241]
**My KSP version**
1.12.4
**Log**
[KSP.log](https://github.com/blowfishpro/B9PartSwitch/files/10793178/KSP.log)
**Description**
B9PartSwitch warn me and says fatal error witch CryoTanks
**Mods Installed**
KerbalEngineer
StockWaterfallEffects
B9PartSwitch (I can delete it without damage to other mods??)
FuelTankPlus
RealisticAtmospheres
999_scale_Redist
HyperDriveMod
RadarAltimeter
Sigma
000_Harmony
000_texturesUnlimited
Deployable engines
DynamicBatteryStorage
FShangarExtender
CommunityTechTree
CryoTanks (The problem)
DecouplerShroud
AirplanePlus
000_filterExtensions
000_FilterExtensions_Config
999_KSP-Recall
IRSequencer
Waterfall
StationPartsExpansionRedux
'I can't continue because is hard'

**Comment by ELJOKER900** [comment]
The error happened because I had not updated it

**Comment by Rodg88** [comment]
You probably also need to install Community Resource Pack, a dependency of CryoTanks

**Comment by ELJOKER900** [comment]
but I already had it
