### ISSUE TITLE
TweakScale interaction broke

### ISSUE THREAD

**Issue by pellinor0** [blowfishpro/B9PartSwitch#26]
http://forum.kerbalspaceprogram.com/index.php?/topic/101540-112-tweakscale-v2212may-20-the-crew-scaling-update/&do=findComment&comment=2631969

my simplified reproduction:
* take stock LFO tank in the editor
* scale to 200% (fuel amount scales correctly)
* switch tank type
* switch tank type back to LFO => fuel amount resets to unscaled values

I tested with the TweakScale dev version. It worked until B9PartSwitch v1.3.1 and broke in version v1.4.0.

**Comment by blowfishpro** [comment]
Yeah, I moved some code around and forgot to include the volume scale.  It's a simple fix so I'll release an update today.
