### ISSUE TITLE
Add configuration property for the number of steps in a tank's UI slider

### ISSUE THREAD

**Issue by rspeed** [blowfishpro/B9PartSwitch#31]
In some situations it would be very handy to have a greater degree of precision when adjusting the amount of resources in a tank while working in the VAB/SPH. Right now the increments are (IIRC) 1/6th the tank's volume, which is particularly problematic when trying to adjust the mass of heavier tanks.

Two examples where this would be useful:

1. Balancing the mass of asymmetrical vehicles, such as a Space Shuttle.
1. Ballast parts, which could be used to keep large vehicles stable at a desired angle during reentry, or as a mass simulator to test the performance of launch vehicles.

The latter example is of particular interest to me, as I've been working on a set of mass simulator parts. The initial version is nearly ready to go, but without the ability to fine-tune the mass, they're not of much use. I'm already using this mod since it allows switching between different ballast materials, and also displays the exact mass of the parts via ModuleB9PartInfo.

I don't know any C#, otherwise I'd make a pull request. Looking at the official API documentation, it seems like this might be possible to implement using [the `stepIncrement` property of `UI_FloatRange`](https://kerbalspaceprogram.com/api/class_u_i___float_range.html), though I'm pretty far out of my element here.

**Comment by blowfishpro** [comment]
I took a look at this ... KSP's resource tweaking slider doesn't actually derive from `UI_FloatRange` and uses a very hard-coded increment of 10% of the resource's max amount.  Unfortunately, I'm not sure there's much I could do here short of re-implementing the resource slider and hacking it in where it goes, or implementing an entirely new interface for resource adjustment.

Could I recommend checking out [Modular Fuel Tanks](http://forum.kerbalspaceprogram.com/index.php?showtopic=58235) or [this mod](http://forum.kerbalspaceprogram.com/index.php?showtopic=150104).  I think they might give you the sort of tank adjustment flexibility that B9PartSwitch was never really built to provide.

Sorry if that sounds a bit defeatist/overly negative.  If you think there's something I've missed in my assessment here, feel free to let me know.

**Comment by rspeed** [comment]
Crud. Time to take this upstream!
