### ISSUE TITLE
Catastrophic failure when a B9_TANK_TYPE contains an invalid resource

### ISSUE THREAD

**Issue by jsolson** [blowfishpro/B9PartSwitch#41]
Easy to reproduce. Create a B9_TANK_TYPE with a resource that does not exist and start KSP. The first exception is thrown at `B9PartSwitch.B9TankSettings.ModuleManagerPostLoad()` and there after every part containing a ModuleB9PartSwitch fails to load with `System.InvalidOperationException: The tank definitions have not been loaded yet (done after game database load). Perhaps ModuleManager is missing or out of date?`.

I'm hesitant to call this a bug, better to make the game unplayable and force the problem to be fixed, however when the parts fail to load any vessels inflight containing those parts are unloaded potentially ruining a save game. Perhaps it could fail a bit more gracefully. Users commonly overlook dependencies which may contain the needed resource definitions when installing mods.

**Comment by blowfishpro** [comment]
Hmm.  It used to be that the game would stop loading at that point, but I guess that behavior might have changed.

I would like this to be more than a silent failure, does it seem reasonable to make the game exit if the tank definitions don't load properly (with lots of information about why in the log of course)?

**Comment by jsolson** [comment]
Game exit would work. I don't think I've ever seen that behavior so I'm not sure how I'd react. Exit with a brief see the log for details message would be better. Folks with slower computers walk away and do other things while MM is loading.
