### ISSUE TITLE
Switching in flight

### ISSUE THREAD

**Issue by blowfishpro** [blowfishpro/B9PartSwitch#49]
Need to come up with a UI to warn when dumping resources

**Comment by jsolson** [comment]
May or may not be helpful, but this is what I'm doing on a wet lab project that I'm having limited success with. I prefer to avoid any sort of modal dialogs.

On the part right click menu, 1 toggle to hide/show the rest of the interface.
A purge tanks toggle
A remove tanks toggle
Mine only removes the tanks, but I could see a selector going here for the new resource setup in your scenario.
A status text line. For what it's doing or why it can't proceed.

The fuel flow shutoff (that green arrow next to the resources) must remain in the off position on all managed resources for anything to happen. Both to insure the resources are not in use and add a few more clicks to avoid accidental activation.

Assuming the fuel flow shutoff requirement is met, when purge is activated the resources are drained one at a time at a configured rate. This can process can be toggled on and off.

Once the resources are all purged, and the fuel flow shutoff requirement is still met, remove tanks will one at a time shrink them (reduce maxAmount) at a configured rate until they reach zero, then delete the resource. This can also be toggled on and off. Shrinking is silly of course, it's mainly to make the reconfiguration something other than instant.

**Comment by blowfishpro** [comment]
Addressed by #50
