### ISSUE TITLE
Switching 'Ladder' transforms results in undesired collider behaviour in the VAB/SPH

### ISSUE THREAD

**Issue by ChrisAdderley** [blowfishpro/B9PartSwitch#55]
While using a ladder transform/collider as a switcher target works very well in the flight scene, in the VAB the colliders used to specify the ladder become collidable and affect surface attachment.

Repro steps:
1. Install SSPX Redux (https://github.com/ChrisAdderley/StationPartsExpansionRedux)
2. Enter VAB
3. Create a PXL-1 'Hostel' Habitation Module
4. Select a surface attachable part and notice it attaching to ladder colliders located along the EVA rails. Notice it not being affected by the ladder collider near the main airlock.

**Comment by blowfishpro** [comment]
I'm not sure why this is breaking, but it seems to work if you don't directly touch the transform that the collider is on - if you parent it to something else and toggle that instead, everything seems to work fine.

**Comment by blowfishpro** [comment]
I don't think there's anything simple I can do about this - something in Unity seems to be getting messed up by turning transforms on and off, but there seems to be a reasonable workaround
