### ISSUE TITLE
Mod does not load AT ALL

### ISSUE THREAD

**Issue by MuricanJeb** [blowfishpro/B9PartSwitch#61]
So I noticed that the actual mod doesn't work AT ALL...
From what i saw in the logs, despite the fact it was in the GameData folder, it did not load at all, as if it didn't exist...

[KSP.log.txt](https://github.com/blowfishpro/B9PartSwitch/files/1424722/KSP.log.txt)

**Comment by blowfishpro** [comment]
Do you have any mods that use B9 Part Switch?  Everything seems to be loading fine but this is just a plugin that doesn't do anything by itself - other mods must add and use the module.

**Comment by MuricanJeb** [comment]
Well, I had this plugin a friend gave me, but other than that, nothing else. Does this require more than module manager, or does it have separate plugins for the toolbar and stuff?

**Comment by blowfishpro** [comment]
B9 Part Switch won't do anything by itself.  It provides a module that other mods can choose to add to parts.  If you don't have any of those other mods installed, you won't see any difference.

**Comment by blowfishpro** [comment]
I would guess that your friend has some of those other mods installed and just got confused or something like that.

**Comment by MuricanJeb** [comment]
Do you know any mods i could use to run B9 Part Switch?

**Comment by blowfishpro** [comment]
Depends on what you're looking for.  B9 Aerospace adds a bunch of parts that themselves have switching, but does not touch the stock parts.  Nertea's Cryogenic Engines and Kerbal Atomics mods both add switching to all the stock tanks as well as adding Liquid Hydrogen engines.

**Comment by MuricanJeb** [comment]
Okay, thanks for all the support :)
