### ISSUE TITLE
Localize hard-coded strings

### ISSUE THREAD

**Issue by Neo2323** [blowfishpro/B9PartSwitch#78]
Hi, thank you for your KSP modding efforts. This is my favorite part switch mod and I would like to see localisation support in it.
KSP now supports many languages and, even if this plugin has not much text in it, it would be really nice to be able to translate it. So everyone can have a UI in their language without mixed words here
and there.
Thank you in advance (even if you are not interested in such a feature) and keep up the good work.

**Comment by blowfishpro** [comment]
Localization mostly just works (up to individual modders to use of course).  I know there are a few built-in strings that aren't localized, are you looking at something in particular?

**Comment by Neo2323** [comment]
Thanks for the reply. Mainly UI elements in the VAB like part info headlines (in example "Switchable Part" or "Subtypes") and maybe resource names (but i guess these are defined in the B9 tank configs). In addition to that, the part switch menu button ("Switch NAMEHERE") and the menu options themself on part windows (there i guess it is only the "Cancel" button and the "Select NAMEHERE" headline).

**Comment by blowfishpro** [comment]
I can add localization support for any hard-coded strings.  Note however that I will not be doing any actual translations, but will accept translation table submissions from users.

Resource names should be using the display name which is localized, I'll add a separate bug for that.

**Comment by Neo2323** [comment]
I see, that is the reason, why resources had english names despite my translations of them. I am happy to hear about your decision to add future localisation support for all strings. Thank you very much!
