### ISSUE TITLE
Stock style node jumping

### ISSUE THREAD

**Issue by CobaltWolf** [blowfishpro/B9PartSwitch#94]
In the stock 1.4 mesh switching, switches that change a node's location rebuild the rocket to reconnect the nodes (instead of leaving them at the original offset). This functionality has been duplicated by DMagic for the Universal Storage plugin, and would be useful for B9 Part Switch.

**Comment by blowfishpro** [comment]
This is working now

**Comment by CobaltWolf** [comment]
cool
